"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Validate = exports.ScopedComponent = exports.Roles = exports.RoleCard = exports.RestrictedRoute = exports.Reset = exports.Register = exports.Permissions = exports.PermissionCard = exports.Login = exports.Forgot = exports.CreateRole = exports.CreatePermission = void 0;
var RestrictedRoute_1 = __importDefault(require("./AUTHENTICATION/components/RestrictedRoute"));
exports.RestrictedRoute = RestrictedRoute_1.default;
var ScopedComponent_1 = __importDefault(require("./AUTHENTICATION/components/ScopedComponent"));
exports.ScopedComponent = ScopedComponent_1.default;
var Forgot_1 = __importDefault(require("./AUTHENTICATION/views/Forgot"));
exports.Forgot = Forgot_1.default;
var Login_1 = __importDefault(require("./AUTHENTICATION/views/Login"));
exports.Login = Login_1.default;
var Register_1 = __importDefault(require("./AUTHENTICATION/views/Register"));
exports.Register = Register_1.default;
var Reset_1 = __importDefault(require("./AUTHENTICATION/views/Reset"));
exports.Reset = Reset_1.default;
var Validate_1 = __importDefault(require("./AUTHENTICATION/views/Validate"));
exports.Validate = Validate_1.default;
var CreatePermission_1 = __importDefault(require("./PERMISSIONS/views/CreatePermission"));
exports.CreatePermission = CreatePermission_1.default;
var PermissionCard_1 = __importDefault(require("./PERMISSIONS/views/PermissionCard"));
exports.PermissionCard = PermissionCard_1.default;
var Permissions_1 = __importDefault(require("./PERMISSIONS/views/Permissions"));
exports.Permissions = Permissions_1.default;
var CreateRole_1 = __importDefault(require("./ROLES/views/CreateRole"));
exports.CreateRole = CreateRole_1.default;
var RoleCard_1 = __importDefault(require("./ROLES/views/RoleCard"));
exports.RoleCard = RoleCard_1.default;
var Roles_1 = __importDefault(require("./ROLES/views/Roles"));
exports.Roles = Roles_1.default;
